services:
  swatch:
    image: ghcr.io/idefixrc/spoolman-swatch-docker:latest
    container_name: spoolman-swatch
    restart: unless-stopped
    ports:
      - "8090:80"
    environment:
      # true: open the app directly instead of the landing page
      - DIRECT_APP_PAGE=false
